# @Day1WebApi_HostAddress = http://localhost:5198
@Day1WebApi_HostAddress = http://localhost:5000
@AccessToken = CfDJ8AhvjefdrPhDu-nDFsJRfqjK5BOffpFXVftOjMfM6PYq672RPzLWl5crt52xIR2mBx_TIrk3Xc_BfG4RZJ-98qy9fC7YlDLTQCVD3eh2jb2J00wgZKrxkrjK4LATr-Dcjx19BGd6OT4MItJ9c2UBghio0koLkgQRXGQdZSlCXWiPauDO8RkR0vvgeCg7vYqD8FONDmISm6javv2jaXYKW66cX572Ho6RFBX8OQfzGo5Nd07oOlxu53oCo76s_DKFnEK7VgmYnY6VnkSbHj-z5Gje9T6MEdixFaLSpKAuS5Km7sdJPNjsWIN8JGgSDbe5hasm0qp-gTUEVXz6LwHDK1xw9GzOjfbfg1Y5ZerbVT_NGvckRRUjMHPRdKQnbTQeQP0-wLiCcPb6Um0LS3eQMhhmEs0gYWrv2jnuyWkbLEXJFYFMvE7GxDTBNchsQjkX82YYXMH0CdkgagEzdgq-teRQ08EGyup4upS41X2g5uYwPPFLsJoPrM1m1qPS2sRlECEtskVQhmRq61IHlqxkSa45cJPhaCdckOR8ZlSOCv8zQL89ch4yShZRmXzixIN_57ya0PrQHSc46fM5B7Ekow0ckcZTQZ3gEY6VIE8j9kw5QVZIqrPziXsXsKdiTuqAL2PYA_HeJdNqZezhb4VjEaeyCSdlhT3HbU9ad6ATShm25UEB5rVuIqHfJUL4TXGsFoyLhIIbSEAMxVlFXNngytRpR5v0NWDXb94CGqPUWlqY3kTAOHFgmaiM5NiHhAoPwkA_fB1ZVzYVR4D5EyCe_BVB9QVKzQ7qz7JI-90kFbW3vcQYF4B-ty2sKC0AP3CbjANTBTBZjdO7G8gQa0XDbpM

GET {{Day1WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Day1WebApi_HostAddress}}/register
Accept: application/json
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "Password123!"
}

###

POST {{Day1WebApi_HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "1234",
  "password": "Pass123!"
}

####

GET {{Day1WebApi_HostAddress}}/api/Pegawai
Accept: application/json
Authorization: Bearer {{AccessToken}}

####

GET {{Day1WebApi_HostAddress}}/api/Pegawai/3fa85f64-5717-4562-b3fc-2c963f66afa6
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Day1WebApi_HostAddress}}/api/Pegawai
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3FA85F64-5717-4562-B3FC-2C963F66AFA6",
  "nama": "Budi",
  "nip": "1235",
  "jabatan": "Pelaksana",
  "gaji": 1000,
  "tanggalMasuk": "2026-08-12"
}

####

PUT {{Day1WebApi_HostAddress}}/api/Pegawai/3FA85F64-5717-4562-B3FC-2C963F66AFA6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3FA85F64-5717-4562-B3FC-2C963F66AFA6",
  "nama": "Budi",
  "nip": "1235",
  "jabatan": "Administrator",
  "gaji": 3000,
  "tanggalMasuk": "2026-08-12"
}

###

POST {{Day1WebApi_HostAddress}}/api/Account/role
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "roleName": "Admin"
}

###

POST {{Day1WebApi_HostAddress}}/api/Account/manage/assign-role
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "email": "dian.gufron@kemenkeu.go.id",
  "roleName": "Admin"
}

###

GET {{Day1WebApi_HostAddress}}/manage/info
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Day1WebApi_HostAddress}}/api/Account/register-pegawai
Accept: application/json
Content-Type: application/json

{
  "nama": "Budi",
  "nip": "1234",
  "jabatan": "Staff",
  "gaji": 1000,
  "tanggalMasuk": "2026-08-12",
  "email": "budi@example.com",
  "password": "Password123!"
}

###

DELETE {{Day1WebApi_HostAddress}}/api/Pegawai/3FA85F64-5717-4562-B3FC-2C963F66AFA6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{Day1WebApi_HostAddress}}/api/Account/manage/info-pegawai
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

PUT {{Day1WebApi_HostAddress}}/api/Kategori/3fa85f64-5717-4562-b3fc-2c963f66afa6
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "nama": "string"
}

###

GET {{Day1WebApi_HostAddress}}/api/Aset
Accept: application/json
Content-Type: application/json
